<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martina Gallardo, Cristóbal Unda, Diego Vicuña">

<title>Adhesión a principios democráticos liberales: entre las percepciones individuales y los contextos nacionales</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="informe_grupo_9_files/libs/clipboard/clipboard.min.js"></script>
<script src="informe_grupo_9_files/libs/quarto-html/quarto.js"></script>
<script src="informe_grupo_9_files/libs/quarto-html/popper.min.js"></script>
<script src="informe_grupo_9_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="informe_grupo_9_files/libs/quarto-html/anchor.min.js"></script>
<link href="informe_grupo_9_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="informe_grupo_9_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="informe_grupo_9_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="informe_grupo_9_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="informe_grupo_9_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="informe_grupo_9_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="informe_grupo_9_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="estilos.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">2</span> Introducción</a></li>
  <li><a href="#antecedentes" id="toc-antecedentes" class="nav-link" data-scroll-target="#antecedentes"><span class="header-section-number">3</span> Antecedentes</a></li>
  <li><a href="#objetivos-e-hipótesis" id="toc-objetivos-e-hipótesis" class="nav-link" data-scroll-target="#objetivos-e-hipótesis"><span class="header-section-number">4</span> Objetivos e hipótesis</a>
  <ul class="collapse">
  <li><a href="#objetivo-general" id="toc-objetivo-general" class="nav-link" data-scroll-target="#objetivo-general"><span class="header-section-number">4.1</span> Objetivo general</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">4.2</span> Objetivos específicos</a></li>
  <li><a href="#hipótesis" id="toc-hipótesis" class="nav-link" data-scroll-target="#hipótesis"><span class="header-section-number">4.3</span> Hipótesis</a>
  <ul class="collapse">
  <li><a href="#nivel-1-individual" id="toc-nivel-1-individual" class="nav-link" data-scroll-target="#nivel-1-individual"><span class="header-section-number">4.3.1</span> Nivel 1 – Individual</a></li>
  <li><a href="#nivel-2-contextual" id="toc-nivel-2-contextual" class="nav-link" data-scroll-target="#nivel-2-contextual"><span class="header-section-number">4.3.2</span> Nivel 2 – Contextual</a></li>
  <li><a href="#interacción" id="toc-interacción" class="nav-link" data-scroll-target="#interacción"><span class="header-section-number">4.3.3</span> Interacción</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#datos-variables-y-métodos" id="toc-datos-variables-y-métodos" class="nav-link" data-scroll-target="#datos-variables-y-métodos"><span class="header-section-number">5</span> Datos, variables y métodos</a>
  <ul class="collapse">
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">5.1</span> Variables</a></li>
  <li><a href="#estadísticos-descriptivos" id="toc-estadísticos-descriptivos" class="nav-link" data-scroll-target="#estadísticos-descriptivos"><span class="header-section-number">5.2</span> Estadísticos descriptivos</a></li>
  </ul></li>
  <li><a href="#modelos-preliminares" id="toc-modelos-preliminares" class="nav-link" data-scroll-target="#modelos-preliminares"><span class="header-section-number">6</span> Modelos preliminares</a></li>
  <li><a href="#análisis-y-resultados-preliminares" id="toc-análisis-y-resultados-preliminares" class="nav-link" data-scroll-target="#análisis-y-resultados-preliminares"><span class="header-section-number">7</span> Análisis y resultados preliminares</a>
  <ul class="collapse">
  <li><a href="#análisis-bivariados" id="toc-análisis-bivariados" class="nav-link" data-scroll-target="#análisis-bivariados"><span class="header-section-number">7.1</span> Análisis bivariados</a></li>
  <li><a href="#modelos" id="toc-modelos" class="nav-link" data-scroll-target="#modelos"><span class="header-section-number">7.2</span> Modelos</a>
  <ul class="collapse">
  <li><a href="#modelo-nulo" id="toc-modelo-nulo" class="nav-link" data-scroll-target="#modelo-nulo"><span class="header-section-number">7.2.1</span> Modelo Nulo</a></li>
  <li><a href="#modelo-con-variables-nivel-1" id="toc-modelo-con-variables-nivel-1" class="nav-link" data-scroll-target="#modelo-con-variables-nivel-1"><span class="header-section-number">7.2.2</span> Modelo con variables nivel 1</a></li>
  <li><a href="#modelo-con-variables-nivel-2" id="toc-modelo-con-variables-nivel-2" class="nav-link" data-scroll-target="#modelo-con-variables-nivel-2"><span class="header-section-number">7.2.3</span> Modelo con variables nivel 2</a></li>
  <li><a href="#modelo-combinado" id="toc-modelo-combinado" class="nav-link" data-scroll-target="#modelo-combinado"><span class="header-section-number">7.2.4</span> Modelo combinado</a></li>
  <li><a href="#modelo-con-pendiente-aleatoria" id="toc-modelo-con-pendiente-aleatoria" class="nav-link" data-scroll-target="#modelo-con-pendiente-aleatoria"><span class="header-section-number">7.2.5</span> Modelo con pendiente aleatoria</a></li>
  <li><a href="#modelo-de-interacción" id="toc-modelo-de-interacción" class="nav-link" data-scroll-target="#modelo-de-interacción"><span class="header-section-number">7.2.6</span> Modelo de interacción</a></li>
  </ul></li>
  <li><a href="#devianza" id="toc-devianza" class="nav-link" data-scroll-target="#devianza"><span class="header-section-number">7.3</span> Devianza</a></li>
  </ul></li>
  <li><a href="#casos-influyentes" id="toc-casos-influyentes" class="nav-link" data-scroll-target="#casos-influyentes"><span class="header-section-number">8</span> Casos influyentes</a></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión"><span class="header-section-number">9</span> Conclusión</a></li>
  <li><a href="#referencias-bibliográficas" id="toc-referencias-bibliográficas" class="nav-link" data-scroll-target="#referencias-bibliográficas"><span class="header-section-number">10</span> Referencias bibliográficas</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Adhesión a principios democráticos liberales: entre las percepciones individuales y los contextos nacionales</h1>
<p class="subtitle lead">Análisis de datos multinivel 2025</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Martina Gallardo, Cristóbal Unda, Diego Vicuña </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">30 de junio de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>Este estudio analiza cómo inciden las percepciones individuales y los climas democráticos nacionales en el respaldo ciudadano a los principios fundamentales de la democracia liberal, como los derechos civiles, la equidad de género y la soberanía popular. La pregunta de investigación se orienta a comprender cómo factores subjetivos y contextuales interactúan para explicar la adhesión normativa a dichos principios. Utilizando datos de la séptima ola del World Values Survey (2017–2022), con una muestra de 88.207 personas en 66 países, se estimaron modelos multinivel que permiten capturar la varianza entre y dentro de los países. El índice de adhesión a la democracia liberal fue construido a partir de tres dimensiones: elecciones libres, derechos civiles y equidad de género. Los resultados indican que tanto la importancia atribuida a vivir en democracia a nivel individual (β ≈ 1.08) como su promedio nacional (β ≈ 1.11) tienen efectos positivos y significativos sobre el respaldo a la democracia liberal. En cambio, el género y la autopercepción económica no mostraron efectos sustantivos. Se concluye que las actitudes democráticas están fuertemente influidas por contextos nacionales, lo que refuerza la utilidad del enfoque multinivel para comprender la cultura política en perspectiva comparada.</p>
</section>
<section id="introducción" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introducción</h1>
<p>Durante la última década, la democracia liberal ha enfrentado múltiples tensiones a nivel global. Pese a que muchos países mantienen formalmente estructuras como elecciones libres, división de poderes y garantías civiles, diversos estudios han evidenciado una creciente insatisfacción ciudadana con el funcionamiento efectivo de los sistemas democráticos, incluso en contextos donde formalmente se mantienen principios como la división de poderes, las elecciones libres o la garantía de derechos civiles (Wike, Silver &amp; Castillo, 2019). Esta paradoja - entre la vigencia normativa de la democracia liberal y su desafección pública - constituye un problema de investigación relevante para las ciencias sociales, ya que pone en cuestión el grado de adhesión sustantiva de la ciudadanía a los principios que estructuran dicho régimen político.</p>
<p>Desde una perspectiva sociológica, el problema se aborda como una tensión entre estructuras normativas y disposiciones subjetivas. Autores como Almond y Verba (1963) entienden la cultura política como un conjunto de orientaciones subjetivas —cognitivas, afectivas y valorativas— hacia el sistema político. Esta noción permite vincular la percepción individual con la legitimidad y estabilidad de los regímenes democráticos, lo que permite preguntarse acerca de cómo distintos tipos de cultura política condicionan la participación democrática y el respaldo a sus principios fundamentales. Inglehart y Welzel (2005b), por su parte, plantean que los valores de autoexpresión y autonomía son claves para el sostén de regímenes democráticos liberales; estos valores se fortalecen en contextos donde los recursos materiales están asegurados y donde la cultura favorece la autoexpresión individual, reforzando el respaldo a la democracia liberal desde una base cultural más profunda. Así, el objeto de estudio de esta investigación son las actitudes ciudadanas frente a los principios fundamentales de la democracia liberal: derechos civiles, igualdad política y límites al poder.</p>
<p>Desde este enfoque, es posible plantear que la percepción subjetiva de vivir en una democracia —así como la valoración que se le atribuye a esta forma de gobierno— actúan como catalizadoresdel respaldo a los principios de la democracia liberal. Esto sugiere una doble dimensión del fenómeno: por un lado, el efecto de la interiorización de valores democráticos en los individuos; y por otro, la influencia del contexto nacional, que puede reforzar o debilitar dicha interiorización. Tal como lo expone la evidencia empírica recogida por Welzel e Inglehart (2005a), las aspiraciones masivas de libertad tienen una capacidad explicativa superior a otras variables estructurales, como el PIB per cápita o el capital social, al analizar el proceso de democratización y su sostenibilidad en el tiempo.</p>
<p>Hasta ahora, buena parte de los estudios comparados han priorizado modelos que se concentran en variables individuales o análisis agregados por país. Esta fragmentación limita la comprensión de cómo el contexto democrático nacional interactúa con las disposiciones individuales. Esta investigación propone superar esta brecha mediante un enfoque multinivel que evalúa simultáneamente el efecto de percepciones individuales (como la importancia atribuida a vivir en democracia) y del clima democrático nacional sobre el respaldo a los valores liberales. Por tanto, se plantea como pregunta de investigación: ¿Cómo inciden las percepciones individuales y los climas democráticos nacionales en el respaldo ciudadano a los principios de la democracia liberal?</p>
<p>Además del foco en la valoración individual de la democracia, se consideran otras dimensiones relevantes como el género y la autopercepción económica. Estudios previos han mostrado que las mujeres suelen presentar actitudes más favorables hacia la equidad y los derechos civiles, mientras que el estatus socioeconómico puede modular la relación entre cultura política y respaldo democrático (Alexander &amp; Welzel, 2011). Del mismo modo, se espera que un mayor consenso contextual respecto a la democracia refuerce las creencias individuales, operando como un mecanismo simbólico de legitimación.</p>
<p>La investigación se basa en datos de la séptima ola del World Values Survey (2017-2022), con una muestra de 88.207 personas en 66 países. La estructura jerárquica de la base de datos permite estimar modelos multinivel que capturen variación entre y dentro de países. Esta estructura jerárquica —personas anidadas dentro de países— justifica plenamente el uso de modelos multinivel, los cuales permiten incorporar predictores en ambos niveles y modelar adecuadamente la variabilidad entre y dentro de los contextos nacionales (Goldstein, 1995; Finch et al., 2014). De este modo, el estudio busca aportar a la literatura sobre cultura política, incorporando un marco teórico-metodológico que articula agencia, estructura y legitimidad democrática.</p>
<p>La variable dependiente del estudio es un índice ad hoc sobre principios de la democracia liberal, que considera dimensiones como la soberanía popular (elecciones libres), la igualdad de género en derechos civiles, y la protección de los derechos individuales frente al Estado. A diferencia de otras medidas más abstractas, este índice operacionaliza la adhesión empírica y evaluativa a principios normativos fundamentales, permitiendo distinguir entre un respaldo retórico a la democracia y un compromiso con sus valores liberales sustantivos (Bellino, 2017; Kong, 2024; Lee, 2024).</p>
<p>Metodológicamente, se sigue una estrategia escalonada. En primer lugar, se estima un modelo nulo sin predictores para evaluar la existencia de varianza significativa entre países. La correlación intraclase (ICC = 0.1489) indica que aproximadamente el 15% de la varianza total del índice depende de diferencias entre contextos nacionales, lo cual valida empíricamente la pertinencia de un enfoque multinivel.</p>
<p>Se estiman modelos multinivel separados a nivel individual (nivel 1) y contextual (nivel 2), los cuales permiten una primera exploración del efecto de las variables incluidas. Sin embargo, al no considerar la estructura anidada de los datos, estos modelos pueden subestimar los errores estándar, inflar falsos positivos y limitar la interpretación de los efectos contextuales (Goldstein, 1995; Finch et al., 2014). Por ello, se procede a la estimación de modelos multinivel con interceptos aleatorios por país, incorporando simultáneamente predictores individuales como el género, la autopercepción socioeconómica y la importancia atribuida a vivir en democracia, junto con predictores contextuales como la percepción media del país sobre la democracia y la valoración promedio de su importancia.</p>
<p>En el modelo multinivel combinado, se observa que las variables “ser mujer” y “autopercepción económica” presentan efectos estadísticamente significativos. Ademas, tanto la “importancia atribuida a vivir en democracia” (coef. ≈ 1.08) como su promedio nacional (coef. ≈ 1.11) tienen efectos positivos y significativos, respaldando las hipótesis H1b y H2b. Esto sugiere que tanto las disposiciones individuales como los climas democráticos nacionales inciden de manera complementaria en el respaldo a principios democráticos liberales.sse estima un modelo con efectos aleatorios en la pendiente de la variable “importancia atribuida a vivir en democracia”, el cual mejora el ajuste general y explica un 3% adicional de la varianza. Si bien en este modelo la variable de autopercepción económica alcanza significancia estadística, su coeficiente es mínimo (≈ -0.02), por lo que se considera irrelevante desde el punto de vista sustantivo. Además, los resultados sugieren un efecto de compensación contextual: en países con mayor adhesión promedio a los principios democráticos, el efecto individual de la importancia atribuida a vivir en democracia tiende a disminuir.</p>
<p>En conjunto, los resultados refuerzan la utilidad del enfoque multinivel para capturar de manera robusta tanto la variabilidad individual como contextual. Esta estrategia metodológica permite una comprensión más profunda y matizada de cómo se configuran las actitudes hacia la democracia liberal, y ha sido validada en investigaciones comparativas recientes (Ariely &amp; Davidov, 2011; Kong, 2024).</p>
</section>
<section id="antecedentes" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Antecedentes</h1>
<p>Desde las investigaciones sociológicas, la cultura política ha sido definida como el conjunto de orientaciones cognitivas, afectivas y valorativas de los ciudadanos hacia su sistema político (Almond &amp; Verba, 1963). Este concepto permite explorar cómo las actitudes subjetivas configuran la legitimidad y estabilidad de los regímenes democráticos. Inglehart y Welzel (2005) extienden esta línea argumental al señalar que el respaldo a la democracia liberal depende de la presencia de valores de autoexpresión y emancipación.&nbsp;Estos valores se desarrollan en contextos con recursos asegurados y climas favorables a la autonomía individual, operando como base cultural profunda del régimen liberal.</p>
<p>La democracia liberal se entiende como un régimen que combina soberanía popular con límites institucionales al poder del Estado, respeto por los derechos individuales y equidad política entre ciudadanos (Offe, 2011). No obstante, su legitimidad ha sido históricamente restringida hacia mujeres y grupos subalternos (Córdoba Gómez, 2008). Por tanto, estudiar su respaldo desde una perspectiva ciudadana exige también considerar sus fronteras normativas, estructurales e históricas.</p>
<p>Las percepciones individuales tienen un papel central en el respaldo a la democracia liberal. Una variable clave es la importancia atribuida a vivir en democracia, la cual ha demostrado ser un indicador robusto del compromiso normativo con el régimen (Welzel &amp; Inglehart, 2005a). También se consideran el género y la autopercepción económica. En promedio, las mujeres presentan actitudes más igualitarias y proclives a la defensa de los derechos civiles (Alexander &amp; Welzel, 2011). Respecto al estatus socioeconómico, su influencia es más ambigua: podría fomentar valores de competencia individual o, por el contrario, reforzar demandas redistributivas en sectores medios.</p>
<p>Además de los factores individuales, este estudio incorpora variables contextuales que capturan el clima democrático nacional: percepción promedio de vivir en democracia e importancia atribuida a la democracia en cada país. Siguiendo a Welzel e Inglehart (2005), estos climas actúan como entornos simbólicos que refuerzan o debilitan las disposiciones individuales. En países con alta valoración democrática, se espera que el respaldo a los principios liberales sea mayor debido a procesos de socialización política más intensos. Desde esta perspectiva, la cultura política se entiende no como un agregado de actitudes individuales, sino como una estructura de sentido compartido (Castro Domingo, 2011).</p>
<p>En suma, este estudio busca aportar no sólo al conocimiento académico, sino también al debate público y político sobre la crisis de legitimidad democrática en distintas partes del mundo. Comprender cómo se configura el respaldo a la democracia liberal desde la interacción entre estructuras y agencia —entre contextos nacionales e historias individuales— es clave para pensar alternativas institucionales y culturales que fortalezcan la vida democrática. En este sentido, la perspectiva sociológica resulta particularmente pertinente, al ofrecer herramientas conceptuales y metodológicas para analizar la complejidad de los vínculos entre subjetividad, cultura política e instituciones.</p>
</section>
<section id="objetivos-e-hipótesis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Objetivos e hipótesis</h1>
<section id="objetivo-general" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="objetivo-general"><span class="header-section-number">4.1</span> Objetivo general</h2>
<p>Analizar cómo inciden las percepciones individuales y los climas democráticos nacionales en el apoyo ciudadano a los principios fundamentales de la democracia liberal a nivel mundial.</p>
</section>
<section id="objetivos-específicos" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">4.2</span> Objetivos específicos</h2>
<ul>
<li><p>Analizar si existen diferencias de género en el respaldo a los principios de la democracia liberal.</p></li>
<li><p>Examinar si la valoración individual de la democracia se asocia con un mayor respaldo a los principios de la democracia liberal.</p></li>
<li><p>Explorar si la autopercepción de pertenencia a un nivel socioeconómico alto se relaciona con un mayor respaldo a los principios de la democracia liberal.</p></li>
<li><p>Evaluar si, en los países donde las personas perciben que viven en un régimen democrático, se observa un mayor respaldo promedio a los principios de la democracia liberal.</p></li>
<li><p>Determinar si, en los países donde la ciudadanía otorga mayor importancia a vivir en democracia, se observa un mayor respaldo promedio a los principios de la democracia liberal.</p></li>
</ul>
</section>
<section id="hipótesis" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="hipótesis"><span class="header-section-number">4.3</span> Hipótesis</h2>
<section id="nivel-1-individual" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="nivel-1-individual"><span class="header-section-number">4.3.1</span> Nivel 1 – Individual</h3>
<ul>
<li><p><span class="math inline">\(H_1a\)</span> (alternativa): Las mujeres presentan un mayor respaldo a los principios de la democracia liberal que los hombres.</p></li>
<li><p><span class="math inline">\(H0_1a\)</span> (nula): No existen diferencias significativas en el respaldo a los principios de la democracia liberal entre hombres y mujeres.</p></li>
<li><p><span class="math inline">\(H_1b\)</span> (alternativa): Las personas que se perciben en una mejor situación económica presentan un mayor respaldo a los principios de la democracia liberal.</p></li>
<li><p><span class="math inline">\(H0_1b\)</span> (nula): La autopercepción de mejor situación económica no se asocia con un mayor respaldo a los principios de la democracia liberal.</p></li>
<li><p><span class="math inline">\(H_1c\)</span> (alternativa): Las personas que valoran positivamente la democracia presentan un mayor respaldo a los principios de la democracia liberal.</p></li>
<li><p><span class="math inline">\(H0_1c\)</span> (nula): Valorar positivamente vivir en democracia no se asocia con un mayor respaldo a los principios de la democracia liberal.</p></li>
</ul>
</section>
<section id="nivel-2-contextual" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="nivel-2-contextual"><span class="header-section-number">4.3.2</span> Nivel 2 – Contextual</h3>
<ul>
<li><p><span class="math inline">\(H_2a\)</span> (alternativa): Los países en los que la ciudadanía percibe que viven en una democracia presentan un mayor respaldo promedio a los principios de la democracia liberal.</p></li>
<li><p><span class="math inline">\(H0_2a\)</span> (nula): La percepción de vivir en una democracia no se asocia con un mayor respaldo promedio a los principios de la democracia liberal.</p></li>
<li><p><span class="math inline">\(H_2b\)</span> (alternativa): Los países donde las personas valoran más vivir en democracia presentan un mayor respaldo promedio a los principios de la democracia liberal.</p></li>
<li><p><span class="math inline">\(H0_2b\)</span> (nula): La valoración promedio de vivir en democracia no se asocia con un mayor respaldo a los principios de la democracia liberal.</p></li>
</ul>
</section>
<section id="interacción" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="interacción"><span class="header-section-number">4.3.3</span> Interacción</h3>
<ul>
<li><p><span class="math inline">\(H_3a\)</span> (alternativa): El efecto positivo del género (a favor de las mujeres) sobre el respaldo a los principios de la democracia liberal es más intenso a medida que el país sea percibido más democrático.</p></li>
<li><p><span class="math inline">\(H0_3a\)</span> (nula): El efecto del género sobre el respaldo a los principios de democracia liberal no se relacionan de manera significativa con la medida en que el país sea percibido como más democrático.</p></li>
</ul>
<p><strong>Modelo teórico con hipótesis</strong> <img src="input/img/modelo_visual.png" class="img-fluid"></p>
</section>
</section>
</section>
<section id="datos-variables-y-métodos" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Datos, variables y métodos</h1>
<p>Se utilizó la base de datos de la séptima ola del World Values Survey (2017–2022), compuesta por 88.207 casos en 66 países. La estructura jerárquica de la base (individuos anidados en países) permite el uso de modelos multinivel. Se eliminaron casos con datos faltantes y se construyó un índice compuesto que captura percepciones sobre tres principios fundamentales de la democracia liberal: soberanía popular, protección de derechos civiles e igualdad de género.</p>
<section id="variables" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="variables"><span class="header-section-number">5.1</span> Variables</h2>
<p>La variable dependiente es el Índice de Percepción sobre Principios de Democracia Liberal (rango: 0–30). Las variables independientes de nivel individual (nivel 1) incluyen: género (1 = mujer), autopercepción de grupo económico e importancia de vivir en democracia. A nivel contextual (nivel 2), se consideran las variables del promedio nacional de percepción sobre cuán democrático es un país e importancia de vivir en un país democrático. El país se incluye como variable de agrupación (cluster).</p>
</section>
<section id="estadísticos-descriptivos" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="estadísticos-descriptivos"><span class="header-section-number">5.2</span> Estadísticos descriptivos</h2>
<div class="cell tbl-cap-location-top">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla 1, descriptivos univariados variables nivel 1</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 37%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">indice_dem</td>
<td style="text-align: left;">indice_dem</td>
<td style="text-align: right;">88207</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.36</td>
<td style="text-align: right;">6.34</td>
<td style="text-align: left;">30 (0-30)</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">país</td>
<td style="text-align: left;">ISO 3166-1 numeric country code</td>
<td style="text-align: right;">88207</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">443.67</td>
<td style="text-align: right;">255.20</td>
<td style="text-align: left;">889 (20-909)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">grp_econ</td>
<td style="text-align: left;">Scale of incomes</td>
<td style="text-align: right;">88207</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: left;">9 (1-10)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">imp_dem</td>
<td style="text-align: left;">Importance of democracy</td>
<td style="text-align: right;">88207</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.38</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: left;">9 (1-10)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">mujer</td>
<td style="text-align: left;">mujer</td>
<td style="text-align: right;">88207</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
</tbody>
</table>
</div>
<p>A nivel individual (nivel 1) hay 88.000 casos, el promedio de adhesión a los principios de la democracia liberales es de 23.4 en una escala del 0 al 30, lo que demuestra que en promedio hay una alta adhesión a los principios democráticos liberales. Respecto a la variable de autopercepción de grupo económico se encuentra al centro de la escala con una media de 4.95 en una escala del 1 al 10. La variable de importancia que se le otorga a la democracia tiene una media de 8.4 en una escala del 1 al 10. El 52% de la muestra son mujeres.</p>
<div class="cell tbl-cap-location-top">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla 2, descriptivos univariados variables nivel 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cuan_dem</td>
<td style="text-align: left;">cuan_dem</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6.08</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: left;">4.25 (3.73-7.98)</td>
</tr>
<tr class="even">
<td style="text-align: left;">prom_imp_dem</td>
<td style="text-align: left;">prom_imp_dem</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.39</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: left;">2.61 (6.94-9.55)</td>
</tr>
</tbody>
</table>
</div>
<p>A nivel contextual (nivel 2) hay 66 países. El promedio nacional de percepción de vivir en democracia es de 6. 08 en una escala del 1 al 10. Y el promedio nacional de importancia atribuida de vivir en democracia es de 8.29 en una escala del 1 al 10; lo que demuestra poca variabilidad entre países.</p>
</section>
</section>
<section id="modelos-preliminares" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Modelos preliminares</h1>
<section id="los-modelos-construidos-son-los-siguientes" class="level4" data-number="6.0.0.1">
<h4 data-number="6.0.0.1" class="anchored" data-anchor-id="los-modelos-construidos-son-los-siguientes"><span class="header-section-number">6.0.0.1</span> Los modelos construidos son los siguientes:</h4>
<p><strong>Anotaciones generales de ecuaciones</strong><br>
</p>
<p><strong>Yij</strong>: Valor del índice de adhesión a principios democráticos liberales del individuo <strong>i</strong> en el país <strong>j</strong>.</p>
<p><strong>Xij</strong>: Variables a nivel individual (nivel 1).</p>
<p><strong>Zj</strong>: Variables a nivel contextual (nivel 2).</p>
<p><strong>eij</strong>: Término de error aleatorio individual.</p>
<p><strong>uoj</strong>, <strong>u1j</strong>: Términos de error aleatorio a nivel país (intercepto y pendiente aleatoria).</p>
<p>Los modelos construidos son los siguientes:</p>
<ul>
<li><strong>Modelo con variables nivel 1</strong>: incluye predictores individuales.</li>
</ul>
<p><span class="math inline">\(Yij = 00 +10+20(mujerij)+ 30(imp_demij)+uoj+ eij\)</span></p>
<p><strong>grp_econij​</strong>: Autoevaluación de grupo económico.</p>
<p><strong>mujerij</strong>: Variable dummy de género (1 = mujer).</p>
<p><strong>imp_demij​</strong>: Importancia atribuida a vivir en democracia.</p>
<ul>
<li><strong>Modelo con variables nivel 2</strong>: incluye predictores contextuales.</li>
</ul>
<p><span class="math inline">\(Yij = 00 +01(cuan_demj)+ 02(prom_imp_demj)+uoj+ eij\)</span></p>
<p><strong>cuan_demj​</strong>: Promedio nacional de evaluación sobre cuán democrático es su país.</p>
<p><strong>prom_imp_demj​</strong>: Promedio nacional de importancia de vivir en democracia.</p>
<ul>
<li><strong>Modelo combinado</strong>: Combina variables de ambos niveles, mostrando que los factores contextuales y personales inciden conjuntamente en el apoyo a la democracia.</li>
</ul>
<p><span class="math inline">\(Yij = 00 +10+20(mujerij)+30(imp_demij)+01(cuan_demj) + 02(prom_imp_demj)+uoj+ eij\)</span></p>
<ul>
<li><strong>Modelo con pendiente aleatoria</strong>: Combina ambos niveles con efectos aleatorios en las pendientes de la variable “Importancia atribuida a vivir en democracia”.</li>
</ul>
<p><span class="math inline">\(Yij = 00 +10+20(mujerij)+30(imp_demij)+01(cuan_demj) + 02(prom_imp_demj)+uoj+u1j(imp_demij)+ eij\)</span></p>
<ul>
<li><strong>Modelo de interacción</strong>: Combina ambos niveles con pendiente aleatoria en variable “género”, más interacción entre la variable “Género” de nivel 1 y “promedio nacional de percepción sobre cuán democrático es un país” de nivel 2.</li>
</ul>
<p><span class="math inline">\(Yij = 00 +10+20(mujerij)+30(imp_demij)+01(cuan_demj) + 02(prom_imp_demj)+ 21(mujerij ⋅ cuan_demj)+uoj+u1j(mujerij)+e\)</span></p>
</section>
</section>
<section id="análisis-y-resultados-preliminares" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Análisis y resultados preliminares</h1>
<section id="análisis-bivariados" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="análisis-bivariados"><span class="header-section-number">7.1</span> Análisis bivariados</h2>
<div class="cell tbl-cap-location-top" data-tbl-cap="Relación entre cuan democratico es percibido un país con índice de adhesión">
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="informe_grupo_9_files/figure-html/fig-1-1.png" id="fig-1" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1
</figcaption>
</figure>
</div>
</div>
<p>En el <a href="#fig-1" class="quarto-xref">Figura&nbsp;1</a> se observa una relación positiva entre la percepción promedio sobre cuán democrático es un país y el nivel de adhesión a principios de la democracia liberal. Por lo que en los países donde la percepción democrática por parte de sus ciudadanos es más alta, también tienden estos mismos a respaldar y adherir a valores liberales fundamentales de la democracia.</p>
<div class="cell tbl-cap-location-top" data-tbl-cap="Relación entre importancia de la democracia por país con índice de adhesión">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="informe_grupo_9_files/figure-html/fig-2-1.png" id="fig-2" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2
</figcaption>
</figure>
</div>
</div>
<p>El <a href="#fig-2" class="quarto-xref">Figura&nbsp;2</a> muestra una clara relación positiva entre el promedio nacional de importancia asignada a vivir en un país democrático y el índice de adhesión a principios de la democracia liberal. Esta pendiente positiva indicaría que en aquellos países donde la democracia es altamente valorada, también existe un mayor grado de internalización de sus principios fundamentales, como las elecciones libres, la igualdad ante la ley y la protección de derechos individuales.</p>
<p>A diferencia del <a href="#fig-1" class="quarto-xref">Figura&nbsp;1</a>, que mostraba la relación entre la percepción institucional de cuán democrático es un país y la adhesión a principios liberales, aquí se destaca el peso del clima político o cultura cívica.</p>
</section>
<section id="modelos" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="modelos"><span class="header-section-number">7.2</span> Modelos</h2>
<p>En la siguiente tabla se presentan los resultados de los modelos descritos en el siguiente orden: Modelo nulo, Modelo con variables nivel 1, Modelo con varaibles nivel 2, combinado, Modelo con pendiente aleatoria y el Modelo interacción entre niveles. Para el cálculo de los parámetros presentados se centraron algunas de las variables independientes, según nivel.</p>
<p>Dentro de las variables de nivel 1, las variables autopercepción de grupo económico e importancia de vivir en democracia fueron centradas a la media del grupo (CWC), para aislar los efectos internos del grupo con los efectos entre ellos.</p>
<p>Las variables de nivel 2 fueron centradas a la media general (CGM), para conservar la variación entre los grupos. Gracias a esto se pueden observar los efectos de las variables de forma más pura; además, se le entrega un sentido al intercepto, que es el de representar para un caso un valor promedio en las variables. Sin embargo, la variable género no fue centrada, dado que su valor 0, ya tenía significado (0 = hombre).</p>
<div class="cell tbl-cap-location-top">
<table style="border-collapse:collapse; border:none;"><caption><p>Tabla 3, Modelos centrados</p></caption>
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Nulo</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Var. Niv. 1 (centrado)</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Var. Niv. 2 (centrado)</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Combinado (centrado)</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Pendiente Aleatoria (centrado)</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Interacción entre niveles</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">std. Error</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">std. Error</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col8">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col9">std. Error</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  0">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  1">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  2">std. Error</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  3">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  4">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  5">std. Error</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  6">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  7">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  8">std. Error</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  9">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">23.32</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.30</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">23.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.30</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">23.34</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1">23.40</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4">23.37</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">23.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">grp econ cmc</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">0.372</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1">-0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3">0.372</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4">-0.02</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6"><strong>0.026</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">-0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9">0.327</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">mujer</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.13</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.04</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1">-0.13</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2">0.04</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4">-0.11</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5">0.04</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6"><strong>0.002</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">-0.11</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.07</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9">0.141</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">imp dem cmc</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.08</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1">1.08</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4">1.08</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5">0.06</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">1.08</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">cuan dem gmc</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.22</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0">0.382</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1">0.22</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3">0.381</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5">0.23</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6">0.976</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">0.27</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9">0.284</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">prom imp dem gmc</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">2.19</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.44</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1">2.19</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2">0.44</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4">2.36</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5">0.40</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">2.19</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.43</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">mujer × cuan dem gmc</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  1"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  2"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  3"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  4"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  5"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  6"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  7">-0.08</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  8">0.07</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  9">0.225</td>
</tr>
<tr>
<td colspan="19" style="font-weight:bold; text-align:left; padding-top:.8em;">Random Effects</td>
</tr>

<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">σ<sup>2</sup></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">34.40</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">29.58</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">34.40</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">29.58</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">28.72</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">29.51</td>
</tr>

<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">τ<sub>00</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">6.02 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">6.03 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">4.18 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">4.19 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">4.04 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">4.03 <sub>país</sub></td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">τ<sub>11</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.20 <sub>país.imp_dem_cmc</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.24 <sub>país.mujer</sub></td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ρ<sub>01</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.41 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">-0.10 <sub>país</sub></td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ICC</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.15</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.17</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.11</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.12</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.15</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.12</td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">N</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">66 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">66 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">66 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">66 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">66 <sub>país</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">66 <sub>país</sub></td>
</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">88207</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">88207</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">88207</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">88207</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">88207</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">88207</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.000 / 0.149</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.119 / 0.268</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.044 / 0.148</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.163 / 0.267</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.165 / 0.286</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.164 / 0.265</td>
</tr>

</tbody></table>

</div>
<section id="modelo-nulo" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="modelo-nulo"><span class="header-section-number">7.2.1</span> Modelo Nulo</h3>
<p>El modelo nulo permite observar parámetros sin la inclusión de variables explicativas. Por ejemplo, según se observa en la tabla 3, se estimó un intercepto de 23,32, correspondiente al promedio del índice de percepción sobre valores de democracia liberal; pero ajustado a la variación entre los grupos, aunque resultando en un valor menor en apenas 0,04 respecto el promedio estimado en los estadísticos descriptivos. Pero lo que demuestra que en promedio hay una alta valoración de principios democráticos liberales, tomando en cuenta que el índice comprende valores del 0 al 30. Luego, también se obtuvo un <span class="math inline">\(\sigma^2\)</span> de 34,40, lo que indica una alta varianza a nivel individual, es decir, dentro de los grupos, mientras que, por otro lado, se calculó un <span class="math inline">\(t_{00}\)</span> de 6,02, lo que indica una varianza más bien moderada a nivel grupal, es decir, entre los grupos.</p>
<p>Dos datos son relevantes principalmente para el cálculo de la correlación intra clase, que en este caso obtuvo un valor de 0,15, lo que quiere decir que el 15% de la variación de la variable dependiente, es decir, del índice de adhesión a los principios de la democracia liberal, es atribuible a diferencias existentes entre los países. Esta estimación es fundamental para la investigación, ya que permite justificar el uso de modelos multinivel, en tanto señala que las diferencias contextuales entre países son significativas, dado que un porcentaje importante de la variación de la dependiente se debe a ellas. De esta manera, se vuelve necesario tomar en consideración los efectos de factores, tanto individuales, como contextuales a nivel de países, para poder obtener una explicación más completa de las variaciones de la valoración de los principios democráticos liberales.</p>
</section>
<section id="modelo-con-variables-nivel-1" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="modelo-con-variables-nivel-1"><span class="header-section-number">7.2.2</span> Modelo con variables nivel 1</h3>
<p>El modelo individual, que estima las relaciones de nivel 1 con la dependiente, presenta un <span class="math inline">\(R^2\)</span> condicional de 0,26, lo que indica que el 26% de la variación del índice de percepción de principios de democracia liberal es explicada por los efectos fijos y aleatorios de las variables explicativas presentes en el modelo. Es decir, este modelo explica poco más de un cuarto de la variación de la variable dependiente.</p>
<p>Respecto a los valores <span class="math inline">\(p\)</span>, las variables “genero” e “importancia de vivir en democracia” son significativas, ambas con valores menores a 0,001. La variable género presenta un coeficiente de -0,13 que indica que ser mujer influye en una disminución de -0,13 en el puntaje obtenido en el índice respecto los hombres, lo que no permite aceptar la hipótesis <span class="math inline">\(H_1a\)</span>, ya que contrario a lo supuesto, el ser mujer no significa un mayor respaldo en la democracia liberal que los hombres, sino que más bien lo contrario. Mientras que la variable “importancia de vivir en democracia”, presenta un beta de 1,08, lo que permite aceptar la hipótesis <span class="math inline">\(H_1c\)</span>, debido a que según lo supuesto, las personas que valoran positivamente la democracia presentan un mayor respaldo a los principios de la democracia liberal, en tanto por cada punto que aumenta la importancia de vivir en democracia, el apoyo a los valores de democracia liberal aumenta en 1,08.</p>
<p>Sin embargo, la variable de autopercepción de grupo económico obtuvo un valor <span class="math inline">\(p\)</span> no significativo, de 0,37, lo que significa que, a diferencia de las otras variables explicativas de nivel 1, no se puede afirmar con certeza que el coeficiente de esta variable pueda observarse en la población y que no se deba al azar. De esta manera, a partir de este modelo no hay evidencia suficiente para rechazar la hipótesis nula <span class="math inline">\(H0_1b\)</span>.</p>
<p>Finalmente, todas las variables explicativas tienen errores estándar bajos, menores de 0.05, por lo que las estimaciones de los efectos son confiables.</p>
</section>
<section id="modelo-con-variables-nivel-2" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="modelo-con-variables-nivel-2"><span class="header-section-number">7.2.3</span> Modelo con variables nivel 2</h3>
<p>Este modelo, que estima las relaciones de las variables de nivel 2 con la dependiente, cuenta con un <span class="math inline">\(R^2\)</span> condicional de 0,148, considerablemente menor que el presentado en el modelo con variables nivel 1. Mientras tanto, según los valores <span class="math inline">\(p\)</span> de las variables, solo el promedio de la importancia de vivir en democracia es significativo, con un valor menor a 0,001. Sin embargo, la variable de promedio nacional de percepción de cuán democrático es un país cuenta con un valor de 0,382, de manera que no es significativa y, por tanto, no existe suficiente evidencia para rechazar <span class="math inline">\(H0_2b\)</span>.</p>
<p>Respecto al coeficiente de regresión de la variable del promedio de la importancia de vivir en democracia, este es de 2,19, lo que indica que por cada punto que aumenta esta variable, el índice aumenta en 2,19 en promedio. De esta manera es posible aceptar <span class="math inline">\(H_2a\)</span>, ya que de acuerdo a este coeficiente, el grado de importancia de se le da a vivir en un régimen democrático en el contexto de cada país, afecta de manera positiva a la adhesión a los principios de democracia liberal por parte de los individuos.</p>
<p>Por último, es importante señalar que los errores estándares de las variables explicativas de este modelo son considerablemente mayores a los del modelo individual, con un error de 0,25 para la variable del promedio de percepción de cuan democratico es un país y 0,44 para el promedio nacional de importancia atribuida a vivir en democracia, sin embargo, en el caso de esta última su error estándar no es grande en relación a su coeficiente.</p>
</section>
<section id="modelo-combinado" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="modelo-combinado"><span class="header-section-number">7.2.4</span> Modelo combinado</h3>
<p>El modelo combinado, que incluye variables de nivel individual y contextual, presenta un <span class="math inline">\(R^2\)</span> condicional de 0,26, al igual que el modelo individual, pero además su <span class="math inline">\(R^2\)</span> marginal también es mayor a los anteriores, de manera que tiene mejor ajuste. También, según los valores <span class="math inline">\(p\)</span> estimados por el modelo, al igual que en los modelos individual y contextual sólo las variables “género” e “importancia de vivir en democracia” de nivel individual y tan solo la variable “promedio de importancia de la democracia” de nivel contextual, son significativas. Por último, los errores estándares también son iguales a los presentados en los modelos individuales y contextuales, lo que indica que no hay colinealidad entre las variables.</p>
</section>
<section id="modelo-con-pendiente-aleatoria" class="level3" data-number="7.2.5">
<h3 data-number="7.2.5" class="anchored" data-anchor-id="modelo-con-pendiente-aleatoria"><span class="header-section-number">7.2.5</span> Modelo con pendiente aleatoria</h3>
<p>El modelo con efectos aleatorios en las pendientes de la variable “Importancia atribuida a vivir en democracia”, mantiene de forma similar la mayoría de los valores “<span class="math inline">\(p\)</span>”, excepto el de “autopercepción del grupo socioeconómico”, que en este modelo pasa a tener un valor <span class="math inline">\(p\)</span> significativo. Sin embargo, su coeficiente de regresión es de -0,02, lo que es un efecto demasiado pequeño para ser considerado importante, aunque en la práctica denote un sentido contrario al supuesto en la hipótesis <span class="math inline">\(H_1b\)</span>, de manera que no es posible aceptarla. Esto indicaría que a medida que la gente se percibe en grupos socioeconómicos más altos, no presenta un mayor respaldo a los principios de la democracia liberal. Sin embargo, tampoco presenta un menor respaldo, de manera que la autopercepción del grupo socioeconómico no tiene un efecto influyente en el apoyo o rechazo de principios de la democracia liberal.</p>
<p>Respecto a los otros coeficientes de las variables explicativas, la variable “importancia de vivir en democracia” mantiene su coeficiente, mientras que el de la variable género disminuye su efecto de -0,13 a -0,11 y el de la variable “promedio de importancia de vivir en democracia” aumenta de 2,19 a 2,36. Sin embargo, estos dos últimos cambios no afectan las estimaciones hechas hasta el momento de las hipótesis.</p>
<p>Por otro lado, se obtuvo un <span class="math inline">\(t_{11}\)</span> de 0,20, lo que significa que hay una variación baja de la pendiente aleatoria entre países. Mientras tanto, el <span class="math inline">\(P_0\)</span> de 0,41, indica que a mayor intercepto, las variables tienen mayor pendiente. En el caso de la variable importancia de la democracia, esto indica que mientras mayor sea el valor del índice de percepción de valores de la democracia liberal cuando esta es 0, en cada grupo, mayor será su efecto, es decir, si de base ya hay adhesión a los principios de la democracia, el valorar que es importante vivir en ella, los reforzará aún más.</p>
<div class="cell tbl-cap-location-top" data-tbl-cap="Interacción entre promedio de percepción de cuan democratico es un país con mujer">
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="informe_grupo_9_files/figure-html/fig-3-1.png" id="fig-3" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3
</figcaption>
</figure>
</div>
</div>
</section>
<section id="modelo-de-interacción" class="level3" data-number="7.2.6">
<h3 data-number="7.2.6" class="anchored" data-anchor-id="modelo-de-interacción"><span class="header-section-number">7.2.6</span> Modelo de interacción</h3>
<p>Se estimó un modelo de interacción entre niveles, estimando la interacción entre la variable mujer (nivel 1) y la variable promedio nacional de percepción de cuán democratico es un país (nivel 2). Para esto, se aleatorizó la pendiente a la variable mujer, para que pudiera variar entre grupos y observar su interacción con la variable nivel 2. A pesar de que la variable de cuán democratico es un país no hubiera sido significativa en los modelos anteriores, tiene sentido haberla usado en este, pues esas significancias referían a su efecto directo y no al efecto que podría tener como moderador de otra variable.</p>
<div class="cell tbl-cap-location-top" data-tbl-cap="Interacción">
<div id="fig-4" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="informe_grupo_9_files/figure-html/fig-4-1.png" id="fig-4" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4
</figcaption>
</figure>
</div>
</div>
<p>La interacción entre género y el promedio de percepción de cuan democrático es un país tuvo un valor <span class="math inline">\(p\)</span> no significativo, de 0,225. De todas formas, el coeficiente de regresión estimado era de -0,08, lo que hubiera significado que, contrario a la hipótesis planteada <span class="math inline">\(H_3a\)</span>, el efecto negativo del género (ser mujer) sobre el respaldo a los principios de la democracia liberal es más intenso a medida que el país sea percibido más democrático. Esto quiere decir, que la diferencia del respaldo a los principios de democracia liberal entre hombres y mujeres es más grande en países percibidos más democráticos, no que las mujeres en promedio sean más antidemocráticas. Sin embargo, esta interacción de todas formas no es significativa.</p>
</section>
</section>
<section id="devianza" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="devianza"><span class="header-section-number">7.3</span> Devianza</h2>
<p>Se estimó un test de devianza para comparar el ajuste de los modelos. Primero, se comparó el Modelo combinado con el Modelo con pendiente aleatoria, como se observa en la siguiente tabla:</p>
<div class="cell tbl-cap-location-top">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla 4, Devianza Modelo combinado y Modelo con pendiente aleatoria</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">npar</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Chisq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Combinado (centrado)</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">549423.9</td>
<td style="text-align: right;">549499.0</td>
<td style="text-align: right;">-274704.0</td>
<td style="text-align: right;">549407.9</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">P.A. Imp_dem</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">547083.7</td>
<td style="text-align: right;">547177.6</td>
<td style="text-align: right;">-273531.9</td>
<td style="text-align: right;">547063.7</td>
<td style="text-align: right;">2344.214</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
<p>A partir de estos resultados, se puede concluir que el modelo con pendiente aleatoria en la variable importancia de la democracia tiene mejor ajuste a la realidad de los datos que el modelo con pendientes fijas. Esta ya que la devianza del modelo con pendiente aleatoria es 2344,2 menor que la del modelo con pendientes fijas, lo que en relación según el <span class="math inline">\(Pr(&gt;Chisq)\)</span> con valor 0, es significativo.</p>
<div class="cell tbl-cap-location-top">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla 5, Devianza Modelo combinado y Modelo de interacción</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">npar</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Chisq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Combinado (centrado)</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">549423.9</td>
<td style="text-align: right;">549499.0</td>
<td style="text-align: right;">-274704.0</td>
<td style="text-align: right;">549407.9</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">P.A. Mujer</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">549324.7</td>
<td style="text-align: right;">549427.9</td>
<td style="text-align: right;">-274651.3</td>
<td style="text-align: right;">549302.7</td>
<td style="text-align: right;">105.2886</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
<p>Por otro lado, como el modelo de interacción se calculó con una pendiente aleatoria distinta (mujer) a la del modelo anterior (Importancia de vivir en democracia), también se hizo un test de devianza, como se observa en la tabla 5, que señaló que el modelo de interacción tenía mejor ajuste que el modelo con pendientes fijas, con una devianza 105,28 menor. Sin embargo, el modelo anterior con pendiente aleatoria en la variable de importancia de vivir en democracia tiene un mejor ajuste, al tener una devianza mucho menor en comparación.</p>
</section>
</section>
<section id="casos-influyentes" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Casos influyentes</h1>
<div id="fig-5" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="informe_grupo_9_files/figure-html/fig-5-1.png" id="fig-5" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5
</figcaption>
</figure>
</div>
<p>Se calculó la distancia de cook para estimar la existencia de casos influyentes que distorsionaran los parámetros de los modelos, como se puede observar en el figura 5, sin embargo, ningún coeficiente cambia de significancia por la eliminación de algún grupo (changed.sig = FALSE). De esta manera se puede afirmar que no hay casos influyentes que distorsionen los parámetros de los modelos.</p>
</section>
<section id="conclusión" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Conclusión</h1>
<p>Los hallazgos confirman que una parte significativa de la varianza de la variable dependiente puede ser explicada por la diferencia entre países (ICC=15%), de manera que se ve confirmada la necesidad de haber estimado modelos multinivel que tomaran en consideración el contexto. Dentro de dichos modelos, fue el modelo que considera variables de ambos niveles y aleatorizando la pendiente de la variable de importancia de vivir en democracia la que tuvo mejor ajuste, es decir, el que se acerca más a la realidad de los datos y, por tanto, en la que nos basamos finalmente para aceptar o rechazar nuestras hipótesis.</p>
<p><strong>Modelo teórico con resultados</strong> <img src="input/img/modelo_teórico_resultados.png" class="img-fluid"></p>
<p>En este sentido, los resultados permitieron rechazar las hipótesis nulas <span class="math inline">\(H0_1a\)</span>, <span class="math inline">\(H0_1c\)</span> y <span class="math inline">\(H0-2b\)</span>, dado que si existía una diferencia entre hombres y mujeres y una influencia de la importancia atribuida a vivir en democracia, tanto a nivel individual como en el contexto, en la adhesión a principios de la democracia liberal. Sin embargo, mientras que <span class="math inline">\(H_1c\)</span> y <span class="math inline">\(H_2b\)</span> fueron aceptadas, estimándose a partir de los modelos la dirección favorable que se creyó que la importancia de vivir en democracia tendría sobre la adhesión a sus principios, esto no sucedió con la variable género, donde la relación fue en sentido contrario. Si bien el efecto no es muy grande (-0,11), que la diferencia sea entre hombres y mujeres muestra que las mujeres son quienes presentan menor adhesión a los principios de la democracia liberal, considerando que el índice incluía una dimensión de igualdad de género llama la atención.</p>
<p>El anterior resultado es llamativo, ya que a partir de la hipótesis inicial consistía en que las mujeres especialmente adhirieran más a los principios que los hombres, ya que son consideradas como sujetos sociales históricamente reprimidos que han luchado por sus derechos civiles, y que apoyan valores y principios emancipativos (Alexander y Welzel, 2011). No obstante, el hecho de que el efecto estimado fuera negativo y de baja magnitud, no refleja necesariamente que existe una identificación con una democracia de tipo liberal, ni que exista una relación o similitud entre sus principios liberales y los de tipo emancipativos.</p>
<p>Un hallazgo interesante fue que, entre las variables que confirmaron las hipótesis, la importancia atribuida a vivir en democracia tuvo un mayor efecto cuando fue medida como una percepción agregada a nivel país. Esto sugiere que no solo influye la valoración individual de la democracia, sino que vivir en un entorno donde la mayoría valora la democracia refuerza significativamente el respaldo a sus principios. Tal como lo indican Ariely y Davidov (2011), los climas culturales e institucionales nacionales actúan como marcos que orientan la interpretación y valoración de los principios democráticos, ejerciendo una influencia adicional sobre las disposiciones individuales. Esto refuerza la idea de que las actitudes no son meramente producto de convicciones personales, sino que están situadas y modeladas por el entorno social, o un clima político.</p>
<p>No hubo evidencia suficiente para rechazar las hipótesis nulas <span class="math inline">\(H0_1b\)</span>, <span class="math inline">\(H0_2a\)</span> y <span class="math inline">\(H0_3a\)</span>, esto podría deberse a que la autopercepción del grupo económico no sea relevante para la adhesión a principios de la democracia. Lo anterior puede ser complementado por Franetovic y Castillo (2022), quienes sugieren que las percepciones sobre la posición económica suelen estar mediadas por narrativas culturales, aspiraciones de clase o juicios morales, lo cual debilita su capacidad explicativa en modelos cuantitativos. Aunque dicho estudio se sitúa en el contexto latinoamericano, sus hallazgos son extrapolables a otras sociedades desiguales, donde muchas personas tienden a subestimar su posición económica o a identificarse con la “clase media” independientemente de su nivel de ingresos. Esta ambigüedad en la autodefinición socioeconómica dificulta establecer asociaciones sólidas entre posición percibida y actitudes políticas, como la adhesión a los principios de la democracia liberal.</p>
<p>El efecto del género puede no estar mediado por cuán democrático se perciba el país, precisamente porque esta segunda variable no es significativa. Asimismo, la escasa relevancia de la interacción entre género y percepción del régimen democrático sugiere que el efecto del género en la adhesión a la democracia liberal opera de forma transversal y no está mediado por el contexto político-institucional evaluado. Esto es coherente con lo planteado por Bellino (2017), quien advierte que la democracia liberal no ha sido lo suficientemente transformadora respecto a las desigualdades estructurales, lo que podría limitar su capacidad de generar adhesión entre sectores históricamente excluidos.</p>
<p>Pero, lo que se puede apuntar con mayor seguridad es que la investigación contó con claras limitaciones. El trabajar principalmente con percepciones tuvo el riesgo de caer en tautologías, donde la variable explicada y la explicativa refirieran a la misma dimensión. Por ejemplo, la variable importancia de vivir en democracia podría llegar a ser demasiado similar a la dependiente, e incluso estimarse que no es necesariamente anterior, o que se refuerzan entre sí. Esto se sostiene con Inglehart y Welzel (2005b), advierten que muchas veces las creencias sobre la democracia y sus principios tienden a agruparse en patrones actitudinales que se refuerzan mutuamente, dificultando la identificación de relaciones causales claras. Esto plantea la necesidad de incorporar en futuros estudios indicadores más objetivos y temporales, que permitan establecer direccionalidades causales más precisas.</p>
<p>Considerar variables que trataten más sobre la realidad material, como la cantidad de casos de corrupción, que podría haber sido una variable interesante, debido a que deterioran el sistema y podrían causar menor apoyo al mismo. Sin embargo, la medición de esta variable debe hacerse con cuidado, no es lo mismo hablar de percepción de corrupción (que podría haber caído dentro del promedio de percepción de cuán democrático es un país), que de casos de corrupción, a la vez que esto último no es lo mismo que hablar de cantidad de dinero malversado. Sin embargo, la base de datos trabajada no contaba con estas dos últimas variables, de manera que queda como desafío para una próxima investigación poder incluir un índice de corrupción por país que considere diversas dimensiones. Como han señalado Kong (2024) y Lee (2024), la desafección hacia la democracia puede deberse más a su mal funcionamiento que a una falta de compromiso con sus principios. Sin embargo, al utilizar una base de datos como la WVS, que no incluye estas variables en su versión estándar, se limita la capacidad de explorar estos factores. Una recomendación para futuras investigaciones es incorporar indicadores como los del Liberal Democracy Index (Our World in Data, 2024), que permiten evaluar con mayor precisión el entorno institucional y su vínculo con las percepciones ciudadanas.</p>
<p>A esto podría sumarse una mejor variable para señalar el grupo socioeconómico que no se base en percepción, y así poder confirmar que esta variable realmente no tenga incidencia. Finalmente, también se admite la necesidad de construir un mejor índice de adhesión a principios de democracia liberal, con datos de otros cuestionarios que aborden de forma más concreta y coherente entre sí las dimensiones de la democracia liberal.</p>
</section>
<section id="referencias-bibliográficas" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Referencias bibliográficas</h1>
<p>Alexander, A. C., &amp; Welzel, C. (2011). Empowering women: The role of emancipative beliefs. European Sociological Review, 27(3), 364–384. https://doi.org/10.1093/esr/jcq012</p>
<p>Almond, G. A., &amp; Verba, S. (1963). The Civic Culture: Political Attitudes and Democracy in Five Nations. Princeton University Press.</p>
<p>Ariely, G., &amp; Davidov, E. (2011). Can we rate public support for democracy in a comparable way? Social Indicators Research, 104(2), 271–286. https://doi.org/10.1007/s11205-010-9693-5</p>
<p>Bellino, M. J. (2017). Democracia liberal y democracia participativa: una tensión no resuelta. Revista LyE, (25), 1–20. http://revistas.derecho.uba.ar/index.php/revistalye/article/view/1037</p>
<p>Castro Domingo, P. (2011). Cultura política: una propuesta socio-antropológica de la construcción de sentido en la política. Región y Sociedad, 23(50), 215–247. http://www.redalyc.org/articulo.oa?id=10218443009</p>
<p>Córdoba Gómez, M. (2008). Democracia liberal y democracia participativa: una tensión no resuelta. Andamios, 5(10), 9–32. https://www.scielo.org.mx/scielo.php?script=sci_arttext&amp;pid=S1870-0063200800030000</p>
<p>Finch, W. H., Bolin, J. E., &amp; Kelley, K. (2014). Multilevel modeling using R. CRC Press. https://doi.org/10.1201/b16042</p>
<p>Franetovic, G., &amp; Castillo, J.-C. (2022). Preferences for income redistribution in unequal contexts: Changes in Latin America between 2008 and 2018. Frontiers in Sociology, 7, 806458. https://doi.org/10.3389/fsoc.2022.806458</p>
<p>Goldstein, H. (1995). Multilevel statistical models (2nd ed.). Edward Arnold.</p>
<p>Inglehart, R., &amp; Welzel, C. (2005a). Modernization, cultural change, and democracy: The human development sequence. Cambridge University Press.</p>
<p>Inglehart, R., &amp; Welzel, C. (2005b). Liberalism, postmaterialism, and the growth of freedom. International Review of Sociology, 15(1), 81–108. https://doi.org/10.1080/03906700500038579</p>
<p>Kong, M. (2024). Individual Perspectives on Liberal Democracy: Insights from World Values Survey. International Journal of High School Research, 6(4), 45–60. https://doi.org/10.36838/v6i4.5</p>
<p>Lee, S. K. (2024). Inequality and the Eroding Base of Liberal Democracy. Social Science Research, 113, 103087. https://doi.org/10.1016/j.ssresearch.2024.103087</p>
<p>Offe, C. (2011). Crisis and innovation of liberal democracy: Can deliberation be institutionalised? Czech Sociological Review, 47(3), 447–472.</p>
<p>Our World in Data. (2024). Liberal Democracy Index – V-Dem Central Estimate, Population-Weighted. OurWorldInData.org. https://ourworldindata.org/grapher/liberal-democracy-index</p>
<p>Wike, R., Silver, L., &amp; Castillo, A. (2019). Many across the globe are dissatisfied with how democracy is working. Pew Research Center. https://www.pewresearch.org/global/2019/04/29/many-across-the-globe-are-dissatisfied-with-how-democracy-is-working/</p>

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>